[package]
name = "aiahr-desugar"
version = "0.1.0"
edition = "2021"

[dependencies]
aiahr-core = { path = "../core" }
bumpalo = "3.1.0"
rustc-hash = "1.1.0"

[dev-dependencies]
aiahr-test = { path = "../test-utils" }
rand = "0.8.5"
