[package]
name = "medir"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base.workspace = true
reducir.workspace = true
pretty.workspace = true
salsa.workspace = true
