[package]
name = "aiahr-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8"

[dev-dependencies]
assert_matches = "1.5" # TODO: use `std` version when stabilized.