[package]
name = "aiahr-optimize-reducir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aiahr-reducir.workspace = true
aiahr-core.workspace = true
