[package]
name = "aiahr-tc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aiahr-core = { path = "../core" }
bumpalo = "3.1.0"
rustc-hash = "1.1.0"
