[package]
name = "aiahr-tc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
assert_matches = "1.5.0"

[dependencies]
aiahr-core = { path = "../core" }
bumpalo = "3.1.0"
ena = "0.14.0"
hashbrown = "0.13.1"
rustc-hash = "1.1.0"
parking_lot = "0.12.1"
