[package]
name = "aiahr-ty"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty.workspace = true

[dependencies]
aiahr-core.workspace = true
salsa.workspace = true