[package]
name = "reducir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base.workspace = true
ty.workspace = true
rustc-hash.workspace = true
pretty.workspace = true
salsa.workspace = true
