[package]
name = "aiahr-emit-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-encoder = "0.32.0"
aiahr-reducir.workspace = true
aiahr-optimize-reducir.workspace = true
